###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "John",
  "surname": "Doe",
  "email": "angel.liberto.ceb@immune.institute",
  "password": "123456",
  "birthdate": "1990-01-01",
  "gender": "Other"
  }


###
GET http://localhost:3000/api/users/all


###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "Angeliyo",
  "surname": "XXX",
  "email": "sexsiuehdui@gmail.com",
  "password": "123456",
  "birthdate": "1999-01-01",
  "gender": "Man"
  }
###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "noam",
  "surname": "XXX",
  "email": "noam@gmail.com",
  "password": "123456",
  "birthdate": "1999-01-01",
  "gender": "Man"
  }

###
POST http://localhost:3000/api/users/googleSignIn
Content-Type: application/json

{
  "givenName": "xxxxx",
  "familyName": "xxxx",
  "email": "dsdsdsdkm@gmail.com",
  "birthday": "1999-01-01",
  "gender": "Man"
  }


  

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "Angel",
  "surname": "Liberto",
  "email": "angelitox@gmail.com",
  "password": "12345678910*",
  "birthdate": "1999-01-01",
  "gender": "Man"
  }

###

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "angelitox@gmail.com",
  "password": "12345678910*"
  }

###
DELETE http://localhost:3000/api/users/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzk1MGZhNTI4YmEyM2JjZTFiYmI1NmYiLCJuYW1lIjoiQW5nZWxpeW8iLCJzdXJuYW1lIjoiWFhYIiwiZW1haWwiOiJzZXhAZ21haWwuY29tIiwiaWF0IjoxNzM3ODI5Mjg4LCJleHAiOjE3NjkzNjUyODh9.A6o8rZWYNOMwwa1zq-NhWX6mzP8qQlhUDkyz-xxg8So

###
PUT http://localhost:3000/api/users/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzk3OGQ4OTk2N2E2MjQ4YTI2NDAxNWEiLCJuYW1lIjoiQW5nZWxpeW8iLCJzdXJuYW1lIjoiWFhYIiwiZW1haWwiOiJzZXhAZ21haWwuY29tIiwiaWF0IjoxNzM3OTkzNDQ1LCJleHAiOjE3Njk1Mjk0NDV9.emAFwVlnR6gCVbv4AKJ1mbJcwsulXzjhSv1R_4_4V3w

{
  "name": "Angeliyo0000xx",
  "surname": "XXX"}

###
GET http://localhost:3000/api/users/send-password-reset-email/67f434753b4bc9f51c66047e