POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "userId": 1,
    "mood": "Neutral",
    "emotions": [],
    "sleep": "Good",
    "health": ["Exercise"],
    "hobbies": ["Read", "Sleep"],
    "food": ["Fruit", "Tacos"],
    "social": [],
    "productivity": [],
    "chores": ["Laundry"],
    "weather": "Sunny",
    "beauty": [],
    "text": "Nice day",
    "images": []
}

###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "userId": 1,
    "mood": "Sad",
    "emotions": ["Sad again"],
    "sleep": "Bad",
    "health": ["Sleep"],
    "hobbies": [],
    "food": [],
    "social": [],
    "productivity": [],
    "chores": ["Laundry"],
    "weather": "Fog",
    "beauty": [],
    "text": "I want to end it all",
    "images": []
}

###

GET http://localhost:3000/api/posts

###

GET http://localhost:3000/api/posts/677a98136433f7fe11a0e332

###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "userId": 2,
    "mood": "Neutral",
    "emotions": ["Happy"],
    "sleepHours": "1-5",
    "sleepQuality": 65,
    "energy": 80,
    "health": ["Sleep"],
    "hobbies": [],
    "food": [],
    "social": [],
    "productivity": [],
    "chores": ["Laundry"],
    "weather": [],
    "beauty": [],
    "text": "Life good",
    "images": []
}