POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "userId": 1,
    "mood": "Neutral",
    "emotions": [],
    "sleep": "Good",
    "health": ["Exercise"],
    "hobbies": ["Read", "Sleep"],
    "food": ["Fruit", "Tacos"],
    "social": [],
    "productivity": [],
    "chores": ["Laundry"],
    "weather": "Sunny",
    "beauty": [],
    "text": "Nice day",
    "images": []
}

###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "userId": 1,
    "mood": "Sad",
    "emotions": ["Sad again"],
    "sleep": "Bad",
    "health": ["Sleep"],
    "hobbies": [],
    "food": [],
    "social": [],
    "productivity": [],
    "chores": ["Laundry"],
    "weather": "Fog",
    "beauty": [],
    "text": "I want to end it all",
    "images": []
}

###

GET http://localhost:3000/api/posts

###

GET http://localhost:3000/api/posts/67f7e1cef9821119bae6838a

###

POST http://localhost:3000/api/posts
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="post"
Content-Type: application/json

{
    "userId": 7,
    "mood": "Sad",
    "emotions": ["Sad again"],
    "sleep": "Bad",
    "health": ["Sleep"],
    "hobbies": [],
    "food": [],
    "social": [],
    "productivity": [],
    "chores": ["Laundry"],
    "weather": ["Fog"],
    "beauty": [],
    "text": "Please work",
    "images": []
}

--boundary
Content-Disposition: form-data; name="files"; filename="landscape1.jpg"
Content-Type: image/jpeg

< ./landscape.jpg

--boundary
Content-Disposition: form-data; name="files"; filename="landscape2.jpg"
Content-Type: image/jpeg

< ./landscape.jpg

--boundary
Content-Disposition: form-data; name="files"; filename="boat.jpg"
Content-Type: image/jpeg

< ./boat.png

--boundary--
